/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ngliaxl_safetykeys_SafetyKeys */

#ifndef _Included_com_ngliaxl_safetykeys_SafetyKeys
#define _Included_com_ngliaxl_safetykeys_SafetyKeys
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ngliaxl_safetykeys_SafetyKeys
 * Method:    nativeAccessKey
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_ngliaxl_safetykeys_SafetyKeys_nativeAccessKey
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
